FROM docker:git
RUN apk add --no-cache bash
RUN mkdir -p /root/.docker/cli-plugins # buildkit
RUN echo '{"experimental": "enabled"}' > /root/.docker/config.json # buildkit
RUN wget -O /root/.docker/cli-plugins/docker-buildx \
  https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64 # buildkit
RUN chmod a+x /root/.docker/cli-plugins/docker-buildx # buildkit
# RUN apk add docker-credential-ecr-login --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
# COPY config.json /root/.docker/
